### PR TITLE
libiconv: fix for Linuxbrew

### PR DESCRIPTION
**Pull request by valkjsaaa**

### CODE REVIEW

**Comment by valkjsaaa** [comment]
It seems when it link it conflict with glibc. Not sure how to solve this problem...

**Comment by sjackman** [comment]
As I recall, `iconv` is provided by `glibc` and so the `libiconv` formula is redundant on Linuxbrew. What do you need it for?

**Comment by valkjsaaa** [comment]
OK. I found one formula build failed because of lack of this library and this library won't build. Probably I should add `glibc` to that formula's dependency.

Thanks!

**Comment by sjackman** [comment]
No need to add `glibc` as a dependency. Change
```ruby
depends_on "libiconv"
```
to
```ruby
depends_on "libiconv" if OS.mac?
```

**Pull request closed without merging**
