### PR TITLE
Merge 2016-09-13

### PR DESCRIPTION
**Pull request by rwhogg**
WORK IN PROGRESS

### CODE REVIEW

**Comment by sjackman** [comment]
```
0.00s==> brew linkage --test global
No broken dylib links
==> PASSED
brew.test.74
==> brew test --verbose global
Testing global
==> /home/linuxbrew/.linuxbrew/Cellar/global/6.5.4/bin/gtags --gtagsconf=/home/linuxbrew/.linuxbrew/Cellar/global/6.5.4/share/gtags/gtags.conf --gtagslabel=default .
/home/linuxbrew/.linuxbrew/Cellar/global/6.5.4/bin/gtags: error while loading shared libraries: libltdl.so.7: cannot open shared object file: No such file or directory
Error: global: failed
<0> expected but was
<127>.
==> FAILED
```
https://travis-ci.org/Linuxbrew/homebrew-dupes/builds/159562302#L4612-L4622

Looks like few packages need to depend on `libtool`.

**Comment by rwhogg** [comment]
> Looks like a few packages need to depend on libtool for libltdl.so.7

With `global` in particular, its head build already depends on `libtool`,  albeit for `:build`. Does Apple's libtool provide the library that it's trying to use (presumably via `dlopen` or similar)? If not, then we might want to send a PR upstream to make `libtool` a `:run` dependency in all cases.

Thoughts @sjackman?

**Comment by sjackman** [comment]
`global` on Mac OS does not depend on `libltdl.dylib`, and Mac OS does not ship with `libltdl.dylib`.
```
❯❯❯ otool -L ~/.homebrew/bin/global
/Users/sjackman/.homebrew/bin/global:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

**Comment by rwhogg** [comment]
Thanks! In that case I can make `global` depend on `libtool`.

**Comment by sjackman** [comment]
Can you report `patchelf --print-needed $(which gtags)`?

**Comment by rwhogg** [comment]
```bash
% patchelf --print-needed ~/.linuxbrew/bin/gtags
libltdl.so.7
libc.so.6
```

**Comment by sjackman** [comment]
Well this is interesting.
```
$ patchelf --print-needed $(which gtags)
libdl.so.2
libc.so.6
```

**Comment by sjackman** [comment]
Can you report `brew gist-logs global`?

**Comment by rwhogg** [comment]
Apparently not...

```
Error: No logs.
```

Peachy.

**Comment by sjackman** [comment]
I didn't have `libtool` installed. Perhaps that's why no `libltdl.so` dependency.
```
checking for dlopen in -ldl... yes
…
checking for lt_dladvise_preload in -lltdl... no
```
https://gist.github.com/sjackman/b7c3f0c118f89ec735ea6dd5062d420b#file-config-log-L914

**Pull request merged**
