### PR TITLE
lapack: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by rwhogg**

### CODE REVIEW

**Comment by maxim-belkin** [comment]
Hmm... the error message on Travis says:
`
/home/linuxbrew/.linuxbrew/opt/sphinx-doc/bin/sphinx-build: /home/linuxbrew/.linuxbrew/Cellar/sphinx-doc/1.4.5/libexec/bin/sphinx-build: /home/linuxbrew/.linuxbrew/bin/python: bad interpreter: No such file or directory
`

**Comment by maxim-belkin** [comment]
So, the problem is in file `/home/linuxbrew/.linuxbrew/Cellar/sphinx-doc/1.4.5/libexec/bin/sphinx-build`. On a Mac, it has `/usr/bin/python` hard-coded. On Linux, it has `/home/linuxbrew/.linuxbrew/bin/python`. Basically, `/usr` is replaced with Linuxbrew's path

**Comment by maxim-belkin** [comment]
Also, I wonder if `-pPorject` is a typo in `sphinx-doc` package.

**Comment by rwhogg** [comment]
The easiest fix is probably something like this :

```patch
-  depends_on :python if OS.mac? && MacOS.version <= :snow_leopard
+  depends_on :python if MacOS.version <= :snow_leopard || (build.bottle? && OS.linux?)
```

But given that `sphinx-doc` has no dependencies *at all*, I don't really get why this is happening at all. I'd guess that it comes from this line:

```ruby
bin.env_script_all_files(libexec/"bin", :PYTHONPATH => ENV["PYTHONPATH"])
```

It's things like this that make me think we need to adopt a broader solution to the problem to hardcoding paths. We've got a bunch of examples now:

* Python (2 & 3)
* libtool
* apr/apr-util
* Ruby
* and now this

CC @sjackman

**Comment by sjackman** [comment]
These commands are all included with Mac OS, which is probably why this issue is specific to Linux. The two options as I see it are:
1. Fix on a case-by-case basis (as we've been doing)
2. Add to the bottling logic to change certain strings like `/usr/bin/gcc-4.8` to `gcc` et c.

**Comment by rwhogg** [comment]
I didn't realize this until now:

https://github.com/Linuxbrew/homebrew-core/pull/720
> sphinx-doc: Remove python dependency for Linuxbrew
    
    cmake depends on sphinx-doc which depends on :python.
    Due to a bug in brew, installing a bottle of a formula with a build
    dependency on cmake causes that formula to have a hard dependency on
    python, which is undesirable.

**Comment by sjackman** [comment]
Yeah, it's not a great situation. I checked with upstream, and it doesn't sound like there's an easy fix, so there's no fix coming soon.

**Comment by sjackman** [comment]
Blocked by https://github.com/Linuxbrew/homebrew-core/issues/1026

**Pull request closed without merging**
