### PR TITLE
Merge 2017-02-06

### PR DESCRIPTION
**Pull request by rwhogg**
Note that `libedit` bumped its soname :frowning:

### CODE REVIEW

**Comment by rwhogg** [comment]
heimdal: https://travis-ci.org/Linuxbrew/homebrew-dupes/builds/199090663#L3160-L3161
```
configure: error: libcurses or libncurses are required!
configure: error: ./configure failed for lib/libedit
```

I'm not sure what gives for this one, but it might be because it was deleted and then restored.

mysql (postinstall): https://travis-ci.org/Linuxbrew/homebrew-dupes/builds/199090663#L4488-L4489
```
2017-02-07T05:12:54.641233Z 0 [ERROR] unknown variable 'key_buffer=256M'
2017-02-07T05:12:54.641258Z 0 [ERROR] Aborting
```

I have to rebuild the bottle for this anyways, so I don't really care.

libiconv: https://travis-ci.org/Linuxbrew/homebrew-dupes/builds/199090663#L4630
```
/bin/sh: 1: gperf: not found
```

libiconv is not needed on Linux

zlib:
```
Error: zlib-1.2.8 already installed
To install this version, first `brew unlink zlib`
```

We don't use homebrew/dupes/zlib for Linuxbrew anyways.

**Comment by sjackman** [comment]
@rwhogg `circle.yml` didn't have the `ci-upload` webhook in it, so you'll have to trigger the webhook manually. e.g.
```
http://bot.linuxbrew.sh/ci-upload/github.com/Linuxbrew/homebrew-dupes/pull/99
```

**Comment by sjackman** [comment]
I've added the webhook: https://github.com/Linuxbrew/homebrew-dupes/commit/b5a05669fa38fda0f688e3a4c36bd0a550a1ff98

**Comment by sjackman** [comment]
I see you've merged four bottles already, so it looks as though you've already figured this out.

**Pull request merged**
