### PR TITLE
Get screen to build

### PR DESCRIPTION
**Pull request by penman**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

-----
Can't say this seems like a. particularly nice way of doing this, but with this change screen does build, which is certainly an improvement.

### CODE REVIEW

**Comment by maxim-belkin** [comment]
@penman: I think the syntax should be something like
```
ENV.append "CFLAGS", "<your change here>"
```

**Comment by sjackman** [comment]
Hi, @penman. Thanks for the fix! Maxim's suggestion is a reasonable solution to avoid overwriting the value of `CFLAGS` that is set by Linuxbrew. Another option is to patch `utmp.c` with something like
```ruby
inreplace "utmp.c", "/* aargh, linux' pututline returns void! */", '#include "utmp.h"'
```

**Comment by penman** [comment]
@sjackman the `inreplace` solution seems like it could be quite fragile, so I went for the `CFLAGS` option.

**Comment by sjackman** [comment]
Sorry I didn't mention earlier, but it should be
```ruby
ENV.append_to_cflags "-include utmp.h" unless OS.mac?
```
`append_to_cflags` modifies `CFLAGS CXXFLAGS OBJCFLAGS OBJCXXFLAGS`
`unless OS.mac?` preserves the existing behaviour on Mac OS (Linuxbrew supports both Mac and Linux.)

**Comment by sjackman** [comment]
I've merged PR #32 to fix the error `configure: error: !!! no tgetent - no screen`.

**Comment by sjackman** [comment]
This PR fixes the error:
```
/home/linuxbrew/.linuxbrew/bin/gcc-5 -c -I. -I.  -isystem/home/linuxbrew/.linuxbrew/include -DETCSCREENRC='"/home/linuxbrew/.linuxbrew/Cellar/screen/4.3.1/etc/screenrc"' -DSCREENENCODINGS='"/home/linuxbrew/.linuxbrew/Cellar/screen/4.3.1/share/screen/utf8encodings"' -DHAVE_CONFIG_H -DGIT_REV=\""`git describe --always 2>/dev/null`"\" \
	     -Os -w -pipe -march=core2 -D_GNU_SOURCE utmp.c
utmp.c: In function 'xpututline':
utmp.c:889:13: error: dereferencing pointer to incomplete type 'struct utmp'
     return u->ut_type == DEAD_PROCESS ? u : 0;
             ^
utmp.c:889:26: error: 'DEAD_PROCESS' undeclared (first use in this function)
     return u->ut_type == DEAD_PROCESS ? u : 0;
                          ^
utmp.c:889:26: note: each undeclared identifier is reported only once for each function it appears in
make: *** [utmp.o] Error 1
```
https://travis-ci.org/Linuxbrew/homebrew-dupes/builds/132988412#L1351

**Comment by sjackman** [comment]
Merged. Thanks for your contribution, @penman!

**Pull request closed without merging**
