### PR TITLE
openldap: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by DoomHammer**

### CODE REVIEW

**Comment by DoomHammer** [comment]
```
curl -I --silent --fail --output /dev/null https://linuxbrew.bintray.com/bottles-dupes/openldap-2.4.43.x86_64_linux.bottle.tar.gz
Error: openldap-2.4.43.x86_64_linux.bottle.tar.gz is already published. Please remove it manually from
https://bintray.com/homebrew/bottles-dupes/openldap/view#files
```

**Comment by sjackman** [comment]
`openldap` already has a bottle: https://github.com/Linuxbrew/homebrew-dupes/blob/master/openldap.rb#L13

**Comment by DoomHammer** [comment]
Interesting why did `build-bottle-pr` open it?

**Comment by sjackman** [comment]
My guess is that your `homebrew/dupes` tap's remote is `homebrew/dupes` rather than the default `linuxbrew/dupes`.

**Comment by DoomHammer** [comment]
It may be so. Sorry for the dupes of dupes then.

**Pull request closed without merging**
